from typing import Any

from src.application.ports.storage import Storage
from src.infrastructure.constants import TTL_FOR_STORAGE


class InMemoryStorage(Storage):
    def __init__(self) -> None:
        self.ttl = TTL_FOR_STORAGE

    # TODO: realize
    async def get(self, key: str) -> dict[str, Any] | None: ...
    async def set(self, key: str, value: Any, ttl: int | None = None) -> None: ...
    async def update(self, key: str, value: Any, ttl: int | None = None) -> None: ...
    async def delete(self, key: str) -> None: ...
    async def expire(self, key: str, ttl: int) -> None: ...
    async def incr(self, key: str) -> Any: ...
    async def incr_with_expire(self, key: str, ttl: int) -> int:
        return 1
