

class ConversationManager:
    async def get_history(self, session_id: str) -> ...: ...
    async def add_user_message(self, question: str, session_id: str) -> ...: ...
    async def add_assistant_message(self, session_id: str, answer: str) -> ...: ...
    async def clear_session(self, session_id: str) -> ...: ...